### ISSUE TITLE
Refresh token not saved after closing the app

### ISSUE THREAD

**Issue by sczitec** [okta/okta-mobile-swift#100]
### Describe the bug?

When logging in we receive a Token that has a refresh token. After refreshing, the refresh token will be changed but after closing the app, the refresh token will be the same as when we logged in. This means that we cannot refresh again if we close the app (the Credential.refresh() function will go into the .failure case of the switch).  This seems like a storing problem

### What is expected to happen?

Refresh token should be changed after refreshing and closing the app

### What is the actual behavior?

Refresh token is the same as when logging in

### Reproduction Steps?

- Log in
- Refresh the token as many times as you want
- Close the app and enter again
- Try to refresh again

### Additional Information?

P.S.: This happens for the whole Token

### SDK Version(s)

1.1.0

**Comment by NachoMan** [comment]
I can't reproduce this with our sample application. Would you be able to share some code samples showing how you're using this feature?

If you wanted to try in our sample app, you can open the OktaMobileSDK.xcworkspace and try the [WebSignIn (iOS)](https://github.com/okta/okta-mobile-swift/tree/master/Samples/WebSignIn) sample.

When you store a token using `[Credential.store](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/credential)`, it will store it within the keychain. Once a refresh succeeds, it should automatically update the value in the keychain with the new tokens.

**Comment by mikenachbaur-okta** [comment]
The `default` property will automatically be assigned when the first token is stored.  For example:

```
try Credential.store(token)

print(Credential.default) // Prints out the credential created above
```

For more information about managing credentials, and in particular how to use the default property, check out the following documentation: https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/managingusercredentials/#Working-with-the-default-credential

That being said, when a refresh is triggered, it should automatically update the corresponding value in the credential storage. Let me try something on my end to see if I can reproduce your issue.

**Comment by mikenachbaur-okta** [comment]
This issue turned out to be difficult to reproduce, but very easy to fix.  I have https://github.com/okta/okta-mobile-swift/pull/108 up to address this issue, and a release will be submitted shortly.

**Comment by Sushree-nayak-2022** [comment]
@mikenachbaur-okta -Thanks for pushing the fix. I quickly tested this on sample app here https://github.com/okta/okta-idx-swift.. but Credential.default is still presenting the old values of token
