### ISSUE TITLE
Revoke is failing with 405

### ISSUE THREAD

**Issue by shanepadgett** [okta/okta-mobile-swift#115]
### Describe the bug?

When I have a valid token stored in Crednential.default and I try to revoke it, it always fails with the following error:
``` bash
network(error: AuthFoundation.APIClientError.statusCode(405))
```

I'm calling the function like such in a SwiftUI app:
```swift
Task {
    do {
        try await Credential.default?.revoke()
    } catch {
        print(error)
    }
}
```

### What is expected to happen?

Revoke should work and credential should be removed

### What is the actual behavior?

Revoke fails and credential remains

### Reproduction Steps?

I follow the steps laid out in the web signin sample to get a credential stored as default. The credential is valid. Trying to revoke as I have shown above then fails for 405.

### SDK Version(s)

1.2.0

**Comment by mikenachbaur-okta** [comment]
Hi @shanepadgett, thank you for reporting this. I'm curious which value is resulting in the 405 error.  As you can see in the [API documentation for the revoke method](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/credential/revoke(type:)), you have the ability to revoke individual tokens (e.g. accessToken, refreshToken, etc), but the default value is `.all`. This subsequently performs multiple separate requests in parallel to ensure all relevant values are revoked.

I'd like to get your help to determine which particular token is resulting in that HTTP 405 error. If you need help in troubleshooting the error, you can either set a breakpoint [here within APIClient.swift](https://github.com/okta/okta-mobile-swift/blob/1.2.0/Sources/AuthFoundation/Network/APIClient.swift#L237), or you can make yourself a delegate of the [`OAuth2ClientDelegate`](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/oauth2clientdelegate) (e.g. `Credential.default?.oauth2.add(delegate: self)`). That's a sub-protocol of [`APIClientDelegate`](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/apiclientdelegate) which has a method [`api(client:didSend:received:)`](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/apiclientdelegate/api(client:didsend:received:)-75hyt) which can be used to intercept errors. From there you can set your own breakpoint to debug the call stack to see what sort of error is occurring.

**Comment by shanepadgett** [comment]
So this looks like a small flub on our end. Our revocation and introspection urls were recently updated in our discovery uri which is believed to be leading to this issue. You can close this ticket because I suspect this will be fixed once those urls are updated.

**Comment by mikenachbaur-okta** [comment]
Sounds good @shanepadgett, thanks for the update. Luckily while investigating your issue I added extra features to the sample app to test revoking individual tokens, and discovered a minor bug in the process. So thank you for inadvertently helping to uncover the bug!

https://github.com/okta/okta-mobile-swift/pull/116
