### ISSUE TITLE
Log In with a user who doesn't have access to the App on OKTA

### ISSUE THREAD

**Issue by mohamed-59** [okta/okta-mobile-swift#123]
### Describe the bug?

I'm testing the demo app, **WebSIgnIn (iOS)**.
I've a valid OKTA configuration 

I've tested different use cases : 
- SignIn
- Display Profile
- Delete the App then install it 
- Log in with a user who doesn't have access to the App on OKTA

### What is expected to happen?

- 1 When we sign out: display a popUp with a signOut  description message
- 2 Have the possibility to change the user

### What is the actual behavior?

- 1 
<img width="260" alt="i1" src="https://user-images.githubusercontent.com/85104778/228581683-867f462b-aace-4c98-ae43-44220f8516e0.png">

- 2 - we can't change the user even if we uninstall then reinstall the app
<img width="356" alt="i2" src="https://user-images.githubusercontent.com/85104778/228582668-270d6c32-0914-43f1-8045-2d589b79c9da.png">

!!
And if we try to sign in, it's looping on opening / closing the browser. 

### Reproduction Steps?

- Log In with a user who doesn't have access to the App on OKTA
- Try to logIn with another user

### SDK Version(s)

1.3.0

**Comment by mikenachbaur-okta** [comment]
It sounds like the browser is caching a cookie / session from a previous log in attempt. How are you signing the user out @mohamed-59?  Unless you use the [WebAuthentication.signOut(from:credential:options:)](https://okta.github.io/okta-mobile-swift/development/webauthenticationui/documentation/webauthenticationui/webauthentication/signout(from:credential:options:)) function (or its [block-based equivalent](https://okta.github.io/okta-mobile-swift/development/webauthenticationui/documentation/webauthenticationui/webauthentication/signout(from:credential:options:completion:))), the cookie won't be cleared in the browser session.

I wrote an article in the API documentation on [how to sign out](https://okta.github.io/okta-mobile-swift/development/webauthenticationui/documentation/webauthenticationui/howtosignout) which you might find helpful.

Finally, you can supply additional parameters at sign-in that can provide a hint to the authorization server for what you would like to have happen.  If you look at the documentation on the [prompt parameter](https://developer.okta.com/docs/reference/api/oidc/#parameter-details), you can see that the default behaviour will be for the user to be silently authenticated in the event a session already exists.

The [signIn(from:options:)](https://okta.github.io/okta-mobile-swift/development/webauthenticationui/documentation/webauthenticationui/webauthentication/signin(from:options:)) function accepts an array of [Options](https://okta.github.io/okta-mobile-swift/development/webauthenticationui/documentation/webauthenticationui/webauthentication/option), one of which controls the prompt behaviour.

So for your sign in action, you can try running code like the following:

```swift
let token = try await WebAuthentication.shared?.signIn(from: view.window, options: [ .prompt(.login) ])
```

Alternatively, you can try to ensure your user is signed out from the browser session.

**Comment by mohamed-59** [comment]
To sign In, I have a WebAuthentication object initialized according to the app env

`var auth: WebAuthentication?`


 ```
func initAuth() {
        // ...
        do {
            if let url = Bundle.main.url(forResource: "Okta_DEV", withExtension: "plist") {
                auth = try WebAuthentication(plist: url)
            }
        } catch {  }
        // ...
    }
```


Sign in and signOut, from a view controller button clicks:


```
@IBAction func signIn0(_ sender: UIButton) {

        auth?.signIn(from: self.viewIfLoaded?.window, options: []) { result in
            switch result {
            case .success(let token):
                print("signIn-OK")
                Credential.default = Credential(token: token)
            case .failure(let error):
                print("signIn-KO")
                print(error.localizedDescription)
            }
            self.ubuttonsVisibility()
        }
    }

```



```
@IBAction func signIn0(_ sender: UIButton) {

        auth?.signIn(from: self.viewIfLoaded?.window, options: []) { result in
            switch result {
            case .success(let token):
                print("signIn-OK")
                Credential.default = Credential(token: token)
            case .failure(let error):
                print("signIn-KO")
                print(error.localizedDescription)
            }
            self.ubuttonsVisibility()
        }
    }
```


```
func setbuttonsVisibility() {

        if Credential.default == nil {
            print("hide logOUT / show logIN")
             // hide logOUT
             // show logIN
        } else {
            print("show logOUT / hide logIN")
            // hide logIN
            // show logOUT
        }
    }
```







Now to reproduce, it is quiet simple, you need:

1_ a valid OKTA configuration for an application with restricted access. 

2_ an okta user account not authorized to use this app with this OKTA configuration.

3_ sign In -> fill the user mail/password


signIn-KO
Authentication error: User is not assigned to the client application. (code 41,297,856).

And signOut not available, and even if i call signOut, i have an error "missingIdToken"


----    

I have also replaced 
```
Credential.default = Credential(token: token)
Credential.default = nil
```
by 

```
try? Credential.store(token)
try? Credential.default?.remove()
```
--> same result


----


And for an okta user account authorized to use this app with this OKTA configuration. Everything is OK.

Click signIn->
signIn-OK
show logOUT / hide logIN

Click signOut->
signOut-OK
hide logOUT / show logIN

**Comment by mikenachbaur-okta** [comment]
Thank you for those reproduction steps and sample code. I'll give this a try locally shortly, and I'll see what I can find out. 

Internal reference: OKTA-597669

**Comment by mikenachbaur-okta** [comment]
Hi @mohamed-59 I was able to reproduce the problem locally, which is definitely odd. My reproduction steps were:

1. Create two Applications in Okta, one the user has access to, and another one that doesn't.
2. Sign in to App "A".
3. I change the client_id in my app settings and attempt to log in again.

I even attempted to pass the `.prompt(.login)` option to force the login screen to show, but that wasn't working for me.

I was able to work around this by setting [ephemeralSession](https://okta.github.io/okta-mobile-swift/development/webauthenticationui/documentation/webauthenticationui/webauthentication/ephemeralsession) to true, which could be an option for you.

I'm going to continue investigating why the [prompt option](https://okta.github.io/okta-mobile-swift/development/webauthenticationui/documentation/webauthenticationui/webauthentication/option/prompt(_:)) isn't working as expected.

**Comment by mikenachbaur-okta** [comment]
One additional note I'd like to add @mohamed-59 is that you shouldn't encounter this issue if you ensure either of the following:

1. That you sign your users out using the `signOut` function (e.g. _do not_ use `remove` or `revoke` explicitly). This will result in the Apple alert being shown to your users during sign out, but that will ensure the session is removed from the user's browser. See [this section of the documentation](https://okta.github.io/okta-mobile-swift/development/webauthenticationui/documentation/webauthenticationui/howtosignout#Using-The-Browser) for more information.
2. Set the [ephemeralSession property](https://okta.github.io/okta-mobile-swift/development/webauthenticationui/documentation/webauthenticationui/webauthentication/ephemeralsession) to `true`. This will ensure the user's existing Okta session will not impact their ability to sign in, and they won't be presented with that error.  This means you should use the `revoke` function to sign the user out. See [this section of the documentation](https://okta.github.io/okta-mobile-swift/development/webauthenticationui/documentation/webauthenticationui/howtosignout#Using-Ephemeral-Sessions) for more information.

If your device or simulator is stuck, because you have a preexisting okta session getting in your way, you can go into Settings -> Safari, and can reset your browser cache.

**Comment by mikenachbaur-okta** [comment]
I'm going to close this issue due to inactivity, but please feel free to reopen the issue in the future if these steps didn't resolve your problem @mohamed-59.
