### ISSUE TITLE
Error in HTTPResponse when fetching or decoding the JWKS

### ISSUE THREAD

**Issue by pxmal** [okta/okta-mobile-swift#124]
### Describe the bug?

I am getting the following error when using

`let token = try await WebAuthentication.shared.signIn(from: view.window)`:

`error oauth2(error: AuthFoundation.OAuth2Error.network(error: AuthFoundation.APIClientError.validation(error: AuthFoundation.JWTError.invalidKey)))`

This is caused by what I believe is the JWKS not being correctly decoded. The JWK uri is discovered correctly by the SDK.

In my setup there are 2 keys to be retrieved, but in the response it is not correct as can be seen in the screenshot (10743243200) - unless of course I have misunderstood something related to JWKS.

When later the fetched token is being validated with the JWK keySet there are no values in the keySet due to the previous error causing the invalidKey error.

The first request that fetches the discovery configuration and the third request that fetches the actual token works fine and as expected. It is only the second request fetching the JWT that causes an error.

These are the keys that are to be retrieved: `{
   "keys":[
      {
         "kid":"{removed}",
         "kty":"RSA",
         "alg":"RSA-OAEP",
         "use":"enc",
         "n":"{removed}",
         "e":"AQAB",
         "x5c":[
            "{removed}"
         ],
         "x5t":"{removed}",
         "x5t#S256":"{removed}"
      },
      {
         "kid":"{removed}",
         "kty":"RSA",
         "alg":"RS256",
         "use":"sig",
         "n":"{removed}",
         "e":"AQAB",
         "x5c":[
            "{removed}"
         ],
         "x5t":"{removed}",
         "x5t#S256":"{removed}"
      }
   ]
}`

The keys are not malformed when using curl etc.

![Screenshot 2023-04-03 at 15 43 33](https://user-images.githubusercontent.com/90321300/229528072-c717ce67-7440-484f-be01-9142a0a7d168.png)

### What is expected to happen?

Retrieval of 2 JWKS

### What is the actual behavior?

Malformed JSON or otherwise wrong retrieval of JWKS

### Reproduction Steps?

Try to fetch JWKs.

### SDK Version(s)

1.3.0

**Comment by pxmal** [comment]
I figured out the problem.

RSA-OAEP is missing from the JWK.Algorithm enum, and we use that in one of our JWKS.
Adding RSA-OAEP it as a case in the enum solves the problem for me.

Is it by choice that is not there?

**Comment by mikenachbaur-okta** [comment]
@pxmal Thank you for the troubleshooting.

There is no explicit reason for that, as I added the algorithms defined as "Required" for JWS. But if your org is also using JWE, those keys will appear in the JWKS results, meaning I should either a) add support for those additional key types, or b) support skipping unknown values.

I'll make sure to fix this, and will let you know when a release is published with the updates.

**Comment by mikenachbaur-okta** [comment]
[1.3.1 has just been released](https://github.com/okta/okta-mobile-swift/releases/tag/1.3.1) which should fix this issue. Please let me know if there's anything else I can do for you.
