### ISSUE TITLE
How to use SAML 2.0 auth with this package?

### ISSUE THREAD

**Issue by hardik99** [okta/okta-mobile-swift#130]
### Describe the feature request?

How to use SAML 2.0 auth with this package?

### New or Affected Resource(s)

How to use SAML 2.0 auth with this package?

**Comment by mikenachbaur-okta** [comment]
This SDK is built around OAuth2 + OIDC, and works exclusively with Bearer tokens. So it isn't compatible with SAML.

**Comment by hardik-frontline** [comment]
is there any Okta SDK that supports Okta SAML? or any example code to integrate SAML in Swift?

**Comment by hardik99** [comment]
is there any Okta SDK that supports Okta SAML? or any example code to integrate SAML in Swift?

**Comment by mikenachbaur-okta** [comment]
Unfortunately no, we don't have any code samples or other SDKs that support SAML use-cases.
