### ISSUE TITLE
`Credential.store` raising error if used with biometrics.

### ISSUE THREAD

**Issue by jiaqi-transcarent** [okta/okta-mobile-swift#150]
### Describe the bug?

Hi there, I'm getting `AuthFoundation.Error: cannotSave(code: -50)` error from running the code snippet below, the issue disappears if `accessControl(.biometryAny)` is removed. I think this might be related: https://stackoverflow.com/questions/34051482/secitemadd-keep-return-50-error-in-swift

```swift
try Credential.store(token,
                     security: [
                         .accessibility(.afterFirstUnlock),
                         .accessControl(.biometryAny),
                     ])
```

### What is expected to happen?

Store the credential in keychain using biometrics.

### What is the actual behavior?

Throws `AuthFoundation.Error: cannotSave(code: -50)`

### Reproduction Steps?

```swift
try Credential.store(token,
                     security: [
                         .accessibility(.afterFirstUnlock),
                         .accessControl(.biometryAny),
                     ])
```

on Xcode 14.3, iOS16.0

### Additional Information?

already made sure Keychain Sharing entitlement is in place.

### SDK Version(s)

from podfile.lock:

```
  - OktaAuthFoundation (1.4.2)
  - OktaAuthSdk (2.4.3)
  - OktaOAuth2 (1.4.2):
    - OktaAuthFoundation (= 1.4.2)
  - OktaOidc (3.10.2):
    - OktaOidc/AppAuth (= 3.10.2)
    - OktaOidc/Okta (= 3.10.2)
  - OktaOidc/AppAuth (3.10.2)
  - OktaOidc/Okta (3.10.2):
    - OktaOidc/AppAuth
  - OktaStorage (1.1.3)
  - OktaWebAuthenticationUI (1.4.2):
    - OktaAuthFoundation (= 1.4.2)
    - OktaOAuth2 (= 1.4.2)
```

**Comment by rajdeepnanua-okta** [comment]
Hi @jiaqi-transcarent, thanks for reporting this issue. @mikenachbaur-okta is the maintainer for this repo, but he is currently on personal time off. He will look into this issue once he's back.

**Comment by mikenachbaur-okta** [comment]
Hi @jiaqi-transcarent, the Keychain APIs are not very clear in their error responses, but typically this means there is some sort of conflicting arguments to the keychain APIs that are resulting in an error.

Are you testing this on a physical device, or on the simulator? Many keychain APIs don't behave correctly when used on the simulator, so you might want to try this first.

Additionally you can look at the [biometric sample](https://github.com/okta/samples-ios/blob/master/browser-sign-in/OktaBrowserSignIn/WelcomeViewController.swift#L95) in the [samples-ios repo](https://github.com/okta/samples-ios) for a comprehensive example. You notice how this example utilizes a context to identify if the policy allows for biometrics to be used.

**Comment by mikenachbaur-okta** [comment]
I'm going to close this ticket due to inactivity. @jiaqi-transcarent if you are still experiencing this issue, please feel free to reopen it, and I'd be happy to help you further.
