### ISSUE TITLE
Relax the requirement of revocation endpoint in the OIDC configuration JSON

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [okta/okta-mobile-swift#160]
### Describe the bug?

I'm trying to use this library to communicate with a configuration that does not provide the revocation endpoint. From my limited reading, this endpoint is not defined by the spec and is an optional feature that some providers implement.

I noticed an earlier change to relax the requirements here: https://github.com/okta/okta-mobile-swift/commit/7c2649c54cb9179817541f4f9504d8b7918d51fe.

Could the same be done to make the revocationEndpoint optional?

### What is expected to happen?

Fetching the well known configuration from a provider should not fail if revocation endpoint is not provided

### What is the actual behavior?

The well known configuration cannot be deserialized and throws an exception disallowing the web authentication sign in from doing anything.

### Reproduction Steps?

1. Invoke the sign in with web UI API connecting to an issuer that doesn't have a revocation endpoint specified in the discovery flow.
2. API throws failed to deserialize error on the revocationEndpoint key

### SDK Version(s)

Version 1.5.0

**Comment by mikenachbaur-okta** [comment]
Hi @SwiftNativeDeveloper, that certainly sounds like a very reasonable request. Thank you for bringing this to my attention, and I'll look into it as soon as I can.

**Comment by SwiftNativeDeveloper** [comment]
@mikenachbaur-okta I made the change locally and got to the next configuration item mismatch. There is some rework that would be needed to address the URL being required in the revoke flow. I force unwrapped to get it to compile :).

After working through that, I ran into another issue. It appears that the claims supported is RECOMMENDED but not required. Thoughts on making that either optional, or if not provided, an empty array? https://github.com/okta/okta-mobile-swift/blob/master/Sources/AuthFoundation/Responses/OpenIdConfiguration.swift#L32

I can open this up as a separate issue if you feel it is necessary.

**Comment by mikenachbaur-okta** [comment]
Yes, all other areas of the SDK were developed directly based on IETF specs and recommendations, but it appears that this particular class is too restrictive.

We can keep this individual issue open to represent the more general "Update OpenIdConfiguration to accommodate optional / unanticipated keys".

Thank you again for pointing this out @SwiftNativeDeveloper

**Comment by SwiftNativeDeveloper** [comment]
@mikenachbaur-okta do you have any roadmap for when this might get addressed?

I started the work last year but then stopped when I realized it would impact public api and prompt a breaking change to an interface: https://github.com/SwiftNativeDeveloper/okta-mobile-swift/commit/e1a8d55d686a9602810efa7e4fa95dbf0ed91f69

**Comment by mikenachbaur-okta** [comment]
Hi @SwiftNativeDeveloper, I've opened #182 which should address your issues.

**Comment by mikenachbaur-okta** [comment]
@SwiftNativeDeveloper Thank you for your patience on this. I've just released 1.7.0 which should resolve this issue. Please let me know if you have any other problems with using a custom authorization server.
