### ISSUE TITLE
How do I access user endpoint using this SDK?

### ISSUE THREAD

**Issue by jiaqi-transcarent** [okta/okta-mobile-swift#164]
### Describe the feature request?

I want to access `passwordChanged` field of a user, but cannot find the corresponding function in this SDK, is it even possible to do that with this SDK? I know `okta-auth-swift` supports it by `OktaAuthStatus.model.embedded?.user?.passwordChanged`

### New or Affected Resource(s)

None

### Provide a documentation link

https://developer.okta.com/docs/reference/api/users/#default-profile-properties

**Comment by mikenachbaur-okta** [comment]
What you're probably looking for is the Credential [userInfo()](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/credential/userinfo()) function to retrieve the user's information from the OAuth2 endpoint.

Note that this SDK is built around OAuth2 standards, and any custom Okta features are not directly supported, but you're free to use Okta's API using the access tokens returned. You can use the Credential's [authorize()](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/credential/authorize(_:)) function to automatically add the appropriate headers to the outgoing URLRequest.

**Comment by jiaqi-transcarent** [comment]
> What you're probably looking for is the Credential [userInfo()](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/credential/userinfo()) function to retrieve the user's information from the OAuth2 endpoint.
> 
> Note that this SDK is built around OAuth2 standards, and any custom Okta features are not directly supported, but you're free to use Okta's API using the access tokens returned. You can use the Credential's [authorize()](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/credential/authorize(_:)) function to automatically add the appropriate headers to the outgoing URLRequest.

Got it, thank you!
