### ISSUE TITLE
Add support for visionOS

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [okta/okta-mobile-swift#171]
### Describe the bug?

There are a few conditional compiles in the SDK that don't have a branch for #elseif os(visionOS). The SDK won't compile when imported by an Apple Vision Pro destination.

### What is expected to happen?

I think everything should 'just work' after the conditional compiles that needed to be added get added. From what I can tell AuthenticationServices is all there on visionOS. 

### What is the actual behavior?

The code won't compile due to missing compiler directive branches for visionOS os type.

### Reproduction Steps?

Create a vision os native app. Add AuthFoundation as a dependency, try to invoke an API.

### SDK Version(s)

1.5.0

### Build Information

Xcode 15.2 or newer, targeting visionOS simulator, any visionOS device, or a real visionOS device.

**Comment by mikenachbaur-okta** [comment]
I wanted to mention that support for visionOS was introduced in #207, and will be included in the next release.
