### ISSUE TITLE
Crash in AuthFoundation with OktaWebAuthenticationUI 1.2.0

### ISSUE THREAD

**Issue by apoorv-trikha-ev** [okta/okta-mobile-swift#180]
### Describe the bug?

Getting:
#3	(null) in specialized _ArrayBuffer._consumeAndCreateNew(bufferIsUnique:minimumCapacity:growForAppend:) ()
in Auth Foundation
<img width="868" alt="Screenshot 2024-03-12 at 5 04 59 PM" src="https://github.com/okta/okta-mobile-swift/assets/135639243/78acb4dc-21f1-4f93-a196-74d36eb53b3e">

Happening when called Credential.refresh()

### What is expected to happen?

App should not crash

### What is the actual behavior?

App is crashing
<img width="868" alt="Screenshot 2024-03-12 at 5 15 41 PM" src="https://github.com/okta/okta-mobile-swift/assets/135639243/9c28ea5c-99f4-407b-95fe-e3c630852e5f">

### Reproduction Steps?

It was intermittent initially but now it is happening quite often that too in prod env.

### SDK Version(s)

OktaWebAuthenticationUI 1.2.0

**Comment by mikenachbaur-okta** [comment]
Thank you for reporting this @apoorv-trikha-ev. I see you're using version 1.2.0. Newer releases add more features, but most importantly #173 might be relevant for your problem.

Would you be able to try the newer version to see if it fixes your problem? If it doesn't, could you send in fully-symbolicated crash logs for this?

**Comment by apoorv-trikha-ev** [comment]
We can close this. @mikenachbaur-okta  Thanks for pointing me to the right fix
