### ISSUE TITLE
Crash in AuthFoundation 1.6.1

### ISSUE THREAD

**Issue by apoorv-trikha-ev** [okta/okta-mobile-swift#181]
### Describe the bug?

We have observed a crash in 1.61.

<img width="1186" alt="image" src="https://github.com/okta/okta-mobile-swift/assets/135639243/e535cabf-2e40-4d97-b56d-75cce1629f77">

### What is expected to happen?

App should not have crashed.

### What is the actual behavior?

App crashed.

### Reproduction Steps?

It happened only once when we were trying to log into the app.

### SDK Version(s)

1.6.1

**Comment by apoorv-trikha-ev** [comment]
Do we have an update on this?

**Comment by apoorv-trikha-ev** [comment]
@mikenachbaur-okta  We don't have a symbolicated crash report

**Comment by mikenachbaur-okta** [comment]
Sorry for the late response @apoorv-trikha-ev. Have you managed to get any crash logs that include what's happening in the other threads? Its unlikely, but this might be a multithreading issue, but I'd like to verify that hypothesis before working on a fix.

**Comment by mikenachbaur-okta** [comment]
@apoorv-trikha-ev I made a [change that should address this problem](https://github.com/okta/okta-mobile-swift/pull/202/files#diff-c8b3fcfe6f58efaeb640f1c49c5923ee5208e211547245b0a2cd655f9defbead), and it was recently [released in version 1.8.2](https://github.com/okta/okta-mobile-swift/releases/tag/1.8.2).  I encourage you to update and see if this fixes your problems.
