### ISSUE TITLE
Support for additional Parameters while initializing OAuth2Client

### ISSUE THREAD

**Issue by rohit3d2003** [okta/okta-mobile-swift#73]
### Describe the feature request?

We are currently using OktaOidc SDK and have leveraged 'additionalParameters' field on OktaOidcConfiguration to trigger few hooks based on incoming parameters. In this new SDK, it would help to be able to pass 'additionalParams' dynamically instead of embedding the value in Okta.plist while creating Flow object (ResourceOwnerFlow in our case). I am trying to prevent 'OAuth2Client' creation by app which can support this technically

### New or Affected Resource(s)

Flow Objects

**Comment by mikenachbaur-okta** [comment]
Thank you for this suggestion @rohit3d2003. This is actually a supported pattern today with the facilities already in place.

The `AuthorizationCodeFlow` (as well as the other flows) support the use of delegation to monitor and customize the flow.  As well, the `WebAuthentication` class exposes its underlying flow, which can allow you to control its behaviour.

You might want to look at the `AuthorizationCodeFlowDelegate.authentication(flow:customizeUrl:)` function. It passes an `inout` URLComponents instance which allows you to change the authorization URL before it gets sent to the browser to load.  In this way, you can change any aspect of the URL dynamically.

Let me know if this works for you, or if there's anything else you'd like to see in this SDK.

**Comment by mikenachbaur-okta** [comment]
That's a good question @rohit3d2003. The Resource Owner flow doesn't redirect through an authorization URL, so additional parameters aren't applicable there. Resource Owner accepts a username and password, and submits those directly to the `/token` endpoint, exchanging it for tokens.

**Comment by rohit3d2003** [comment]
Coming from OktaOidc v3.11.2, we have an authentication flow where we collect username and password (Custom iOS screen), calls OktaAuthSdk.authenticate which returns a session token and subsequently call OktaOIDC.authenticate with session token to generate accessToken, IdToken etc. OktaOIDC client has 'additionalParameters' as part of it's configuration. If we were to replace this with new SDK, what would be the new workflow? As mentioned earlier, we have pre-hooks on the Okta side based on this additionalParameters that client provides.

**Comment by mikenachbaur-okta** [comment]
If you're using OktaAuthSdk, you should use the `SessionTokenFlow` to exchange the session token you receive from the `OktaAuthSdk.authenticate` call, and exchange it with a code.  That flow accepts `additionalParameters`.

**Comment by mikenachbaur-okta** [comment]
This should help you out with what you want to do. You can include the appropriate scope when authenticating to get the Device Secret, at which point you can use the TokenExchangeFlow to generate new tokens for other applications.

And yes, we haven't released a new beta since we're hoping to release 1.0 soon. You're more than welcome to develop against master since it is quite stable at the moment, and very few changes are planned prior to our GA release.

**Comment by rohit3d2003** [comment]
We are all set for now. Thanks @mikenachbaur-okta
