### ISSUE TITLE
Character "+" gets replaced with " " (space) when added in "login_hint" as additionalParameter when using signIn from WebAuthentication

### ISSUE THREAD

**Issue by sczitec** [okta/okta-mobile-swift#98]
### Describe the bug?

I'm trying to sign in using a login hint to open a register view instead of a login view from the IDS the web view). The app has the send a phone number as an additional paramter in the login_hint to do this. The phone number can contain a "+" at the begining.

When adding "login_hint" as additional parameter (either when creating WebAuthentication or in Okta.plist) and using the signIn method of WebAuthentication every "+" character in the "login_hint" will be replaced with a " " (space)

Is the package removing any "+" in the login_hint or is this a problem from the IDS?

### What is expected to happen?

Send the string exactly the way it is, with the "+" 

### What is the actual behavior?

The "+" gets replaced with a " " (space)

### Reproduction Steps?

- Create a WebAuthentication with a login hint
- Use the signIn methob (WebAuthentication.shared.signIn...)
- All the "+" characters in the "login_hint" will be replaced with a " " when the web view is opened

### Additional Information?

A colleague from the android team can send the "+" to the same IDS server

### SDK Version(s)

1.1

**Comment by mikenachbaur-okta** [comment]
Thank you for bringing this to my attention @sczitec, I'll take a look at this shortly.

**Comment by mikenachbaur-okta** [comment]
Internal reference: [OKTA-544094](https://oktainc.atlassian.net/browse/OKTA-544094)

**Comment by sczitec** [comment]
A quick fix i made is adding the following code in AuthorizationCodeFlow+Extensions in authenticationComponents function (and commenting the components.queryItems above):
 ```
       var cs = CharacterSet.urlQueryAllowed
        cs.remove("+")
        components.percentEncodedQuery = queryParameters(using: context).map {
            $0.addingPercentEncoding(withAllowedCharacters: cs)!
            + "=" + $1.addingPercentEncoding(withAllowedCharacters: cs)!
        }.joined(separator: "&")

```
I see there is a similar approach in FormatDataExtensions but the characterSet and the function inside here are never called (or at least i don't know how to use them).

**Comment by mikenachbaur-okta** [comment]
Thank you @sczitec, I'm working on this bug fix this week, so I'll tag you when the PR is available.

**Comment by NachoMan** [comment]
@sczitec Version 1.1.1 has just been released, with this bug fix applied.
